package com.cfd.board.sub.server.entitiy;

/**
 * @Title:  ServerInfo
 * @Package:  com.cfd.board.sub.server.entitiy
 * @Description:  
 * @author ChenWeiYu
 * @date 2019年02月22日 23:27
 * @version v1.0 
 */
public class ServerInfo {
    /**
     * 信息id
     */
    private Integer infoId;

    /**
     * 服务器名称
     */
    private String infoName;

    /**
     * 服务器ip
     */
    private String infoIp;

    /**
     * 服务器地址
     */
    private String infoUrl;

    /**
     * 服务器用户名
     */
    private String infoUser;

    /**
     * 服务器密码
     */
    private String infoPwd;

    /**
     * 数据库用户名
     */
    private String infoDataUser;

    /**
     * 数据库密码
     */
    private String infoDataPwd;

    /**
     * 数据库地址
     */
    private String infoDataUrl;

    /**
     * 数据库类型：1 Mysql 2 Oracle
     */
    private Integer infoDataType;

    /**
     * 备注
     */
    private String infoDesc;

    /**
     * 创建人id
     */
    private Integer createUserId;

    /**
     * 创建人姓名
     */
    private String createUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_ID
     *
     * @return the value of cfd_server_info.INFO_ID
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public Integer getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_ID
     *
     * @param infoId the value for cfd_server_info.INFO_ID
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_NAME
     *
     * @return the value of cfd_server_info.INFO_NAME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getInfoName() {
        return infoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_NAME
     *
     * @param infoName the value for cfd_server_info.INFO_NAME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoName(String infoName) {
        this.infoName = infoName == null ? null : infoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_IP
     *
     * @return the value of cfd_server_info.INFO_IP
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getInfoIp() {
        return infoIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_IP
     *
     * @param infoIp the value for cfd_server_info.INFO_IP
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoIp(String infoIp) {
        this.infoIp = infoIp == null ? null : infoIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_URL
     *
     * @return the value of cfd_server_info.INFO_URL
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getInfoUrl() {
        return infoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_URL
     *
     * @param infoUrl the value for cfd_server_info.INFO_URL
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoUrl(String infoUrl) {
        this.infoUrl = infoUrl == null ? null : infoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_USER
     *
     * @return the value of cfd_server_info.INFO_USER
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getInfoUser() {
        return infoUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_USER
     *
     * @param infoUser the value for cfd_server_info.INFO_USER
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoUser(String infoUser) {
        this.infoUser = infoUser == null ? null : infoUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_PWD
     *
     * @return the value of cfd_server_info.INFO_PWD
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getInfoPwd() {
        return infoPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_PWD
     *
     * @param infoPwd the value for cfd_server_info.INFO_PWD
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoPwd(String infoPwd) {
        this.infoPwd = infoPwd == null ? null : infoPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_DATA_USER
     *
     * @return the value of cfd_server_info.INFO_DATA_USER
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getInfoDataUser() {
        return infoDataUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_DATA_USER
     *
     * @param infoDataUser the value for cfd_server_info.INFO_DATA_USER
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoDataUser(String infoDataUser) {
        this.infoDataUser = infoDataUser == null ? null : infoDataUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_DATA_PWD
     *
     * @return the value of cfd_server_info.INFO_DATA_PWD
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getInfoDataPwd() {
        return infoDataPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_DATA_PWD
     *
     * @param infoDataPwd the value for cfd_server_info.INFO_DATA_PWD
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoDataPwd(String infoDataPwd) {
        this.infoDataPwd = infoDataPwd == null ? null : infoDataPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_DATA_URL
     *
     * @return the value of cfd_server_info.INFO_DATA_URL
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getInfoDataUrl() {
        return infoDataUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_DATA_URL
     *
     * @param infoDataUrl the value for cfd_server_info.INFO_DATA_URL
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoDataUrl(String infoDataUrl) {
        this.infoDataUrl = infoDataUrl == null ? null : infoDataUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_DATA_TYPE
     *
     * @return the value of cfd_server_info.INFO_DATA_TYPE
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public Integer getInfoDataType() {
        return infoDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_DATA_TYPE
     *
     * @param infoDataType the value for cfd_server_info.INFO_DATA_TYPE
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoDataType(Integer infoDataType) {
        this.infoDataType = infoDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.INFO_DESC
     *
     * @return the value of cfd_server_info.INFO_DESC
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getInfoDesc() {
        return infoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.INFO_DESC
     *
     * @param infoDesc the value for cfd_server_info.INFO_DESC
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setInfoDesc(String infoDesc) {
        this.infoDesc = infoDesc == null ? null : infoDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.CREATE_USER_ID
     *
     * @return the value of cfd_server_info.CREATE_USER_ID
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.CREATE_USER_ID
     *
     * @param createUserId the value for cfd_server_info.CREATE_USER_ID
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_info.CREATE_USER_NAME
     *
     * @return the value of cfd_server_info.CREATE_USER_NAME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_info.CREATE_USER_NAME
     *
     * @param createUserName the value for cfd_server_info.CREATE_USER_NAME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }
}