package com.cfd.board.sub.server.entitiy;

import java.util.Date;

/**
 * @Title:  ServerGroup
 * @Package:  com.cfd.board.sub.server.entitiy
 * @Description:  
 * @author ChenWeiYu
 * @date 2019年02月22日 23:27
 * @version v1.0 
 */
public class ServerGroup {
    /**
     * 分组id
     */
    private Integer groupId;

    /**
     * 分组名称
     */
    private String groupName;

    /**
     * 分组排序
     */
    private Integer groupSeq;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 创建人id
     */
    private Integer createUserId;

    /**
     * 创建人姓名
     */
    private String createUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_group.GROUP_ID
     *
     * @return the value of cfd_server_group.GROUP_ID
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_group.GROUP_ID
     *
     * @param groupId the value for cfd_server_group.GROUP_ID
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_group.GROUP_NAME
     *
     * @return the value of cfd_server_group.GROUP_NAME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_group.GROUP_NAME
     *
     * @param groupName the value for cfd_server_group.GROUP_NAME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_group.GROUP_SEQ
     *
     * @return the value of cfd_server_group.GROUP_SEQ
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public Integer getGroupSeq() {
        return groupSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_group.GROUP_SEQ
     *
     * @param groupSeq the value for cfd_server_group.GROUP_SEQ
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setGroupSeq(Integer groupSeq) {
        this.groupSeq = groupSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_group.CREATE_TIME
     *
     * @return the value of cfd_server_group.CREATE_TIME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_group.CREATE_TIME
     *
     * @param createTime the value for cfd_server_group.CREATE_TIME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_group.CREATE_USER_ID
     *
     * @return the value of cfd_server_group.CREATE_USER_ID
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_group.CREATE_USER_ID
     *
     * @param createUserId the value for cfd_server_group.CREATE_USER_ID
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfd_server_group.CREATE_USER_NAME
     *
     * @return the value of cfd_server_group.CREATE_USER_NAME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfd_server_group.CREATE_USER_NAME
     *
     * @param createUserName the value for cfd_server_group.CREATE_USER_NAME
     *
     * @mbg.generated Fri Feb 22 23:27:16 CST 2019
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }
}